services:
  db:
    image: postgres:16.0-bookworm
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - db_net
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.8
    profiles:
      - "inspect_db"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_DEFAULT_USER_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_DEFAULT_USER_PASSWORD}
    networks:
      - db_net
    ports:
      - ${PG_ADMIN_PORT}:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

  smtp:
    image: mailhog/mailhog:v1.0.1
    profiles:
      - "debug"
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - smtp_net

  search:
    image: public.ecr.aws/opensearchproject/opensearch:2
    restart: always
    healthcheck:
      interval: 10s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/
    environment:
      cluster.name: fusionauth
      discovery.type: single-node
      node.name: search
      plugins.security.disabled: true
      bootstrap.memory_lock: true
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: 1024
        hard: 2048
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    volumes:
      - search_data:/usr/share/opensearch/data
    networks:
      - search_net

  fusionauth:
    image: fusionauth/fusionauth-app:1.49.2
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9011/api/status || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
    depends_on:
      db:
        condition: service_healthy
      search:
        condition: service_healthy
    environment:
      ADMIN_EMAIL: ${AUTH_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${AUTH_ADMIN_PASSWORD}
      ALLOWED_ORIGIN: ${UI_ORIGIN}
      API_KEY__APP_SERVER: ${AUTH_API_KEY__APP_SERVER}
      API_KEY__SUPER_ADMIN: ${AUTH_API_KEY__SUPER_ADMIN}
      APPLICATION_ID: ${AUTH_APPLICATION_ID}
      APPLICATION_NAME: ${AUTH_APPLICATION_NAME}
      ASYMMETRIC_KEY_ID: ${AUTH_ASYMMETRIC_KEY_ID}
      CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      DATABASE_PASSWORD: ${AUTH_DATABASE_PASSWORD}
      DATABASE_ROOT_PASSWORD: ${DB_PASSWORD}
      DATABASE_ROOT_USERNAME: ${DB_USERNAME}
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_USERNAME: ${AUTH_DATABASE_USERNAME}
      DEFAULT_TENANT_ID: ${AUTH_DEFAULT_TENANT_ID}
      EMAIL_HOST: ${AUTH_EMAIL_HOST}
      EMAIL_PORT: ${AUTH_EMAIL_PORT}
      EMAIL_PASSWORD: ${AUTH_EMAIL_PASSWORD}
      EMAIL_USERNAME: ${AUTH_EMAIL_USERNAME}
      EMAIL_TEMPLATE_FROM_ADDRESS: ${AUTH_EMAIL_TEMPLATE_FROM_ADDRESS}
      EMAIL_TEMPLATE_FROM_NAME: ${AUTH_EMAIL_TEMPLATE_FROM_NAME}
      EXTERNAL_URL: ${AUTH_EXTERNAL_URL}
      FUSIONAUTH_APP_KICKSTART_FILE: ${AUTH_FUSIONAUTH_APP_KICKSTART_FILE}
      FUSIONAUTH_APP_MEMORY: ${AUTH_FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: ${AUTH_FUSIONAUTH_APP_RUNTIME_MODE}
      GROUP__ORGANIZATION_ADMINISTRATORS_ID: ${AUTH_GROUP__ORGANIZATION_ADMINISTRATORS_ID}
      GROUP__PATIENTS_ID: ${AUTH_GROUP_ID__PATIENTS}
      GROUP__SUBSCRIPTION_BUSINESS_ANNUAL_ID: ${AUTH_GROUP__SUBSCRIPTION_BUSINESS_ANNUAL_ID}
      GROUP__SUBSCRIPTION_STARTUP_ANNUAL_ID: ${AUTH_GROUP__SUBSCRIPTION_STARTUP_ANNUAL_ID}
      LOGOUT_URL: ${AUTH_LOGOUT_URL}
      ROLE__BTX_ASSISTANT_READ_WRITE_ID: ${AUTH_ROLE__BTX_ASSISTANT_READ_WRITE_ID}
      ROLE__BTX_ASSISTANT_READ_WRITE_NAME: ${AUTH_ROLE__BTX_ASSISTANT_READ_WRITE_NAME}
      ROLE__ORGANIZATION_ADMINISTRATOR_ID: ${AUTH_ROLE__ORGANIZATION_ADMINISTRATOR_ID}
      ROLE__ORGANIZATION_ADMINISTRATOR_NAME: ${AUTH_ROLE__ORGANIZATION_ADMINISTRATOR_NAME}
      ROLE__PATIENT_ID: ${AUTH_ROLE__PATIENT_ID}
      ROLE__PATIENT_NAME: ${AUTH_ROLE__PATIENT_NAME}
      SEARCH_SERVERS: http://search:9200
      SEARCH_TYPE: elasticsearch
      WEBHOOK_URL: ${AUTH_WEBHOOK_URL}
    networks:
      - db_net
      - search_net
      - smtp_net
      - web_net
    ports:
      - 9011:9011
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config
      - ./.fusion-auth:/usr/local/fusionauth/kickstart

  web-api:
    image: ${WEB_API_IMAGE:-258996848737.dkr.ecr.us-east-1.amazonaws.com/medspaah:latest}
    profiles:
      - prod
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4242/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
      fusionauth:
        condition: service_healthy
    environment:
      WEB_API_UPSERT_SEED_DATA: ${WEB_API_UPSERT_SEED_DATA}
    networks:
      - db_net
      - web_net
    ports:
      - 4242:4242

  web-proxy:
    image: nginx:1.27
    profiles:
      - prod
    restart: always
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ${UI_FILES_DIR}:/usr/share/nginx/html:ro
    depends_on:
      - fusionauth
      - web-api
    networks:
      - web_net

networks:
  db_net:
    driver: bridge
  search_net:
    driver: bridge
  smtp_net:
    driver: bridge
  web_net:
    driver: bridge

volumes:
  db_data:
  pgadmin_data:
  fusionauth_config:
  search_data:
